version: '3.7'

services:
  database_omunga: 
    image: postgres:9.4
    container_name: database_omunga
    tty: true
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/data/postgres
    networks:
      - omunga
  app:
    build: .
    container_name: omunga_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    command: "yarn dev"
    env_file:
      - .env
    volumes:
      - .:/usr/app
    networks:
      - omunga
    depends_on:
      - database_omunga

networks:
  omunga: {}

volumes:
  pgdata:
    

