version: '3.7'

services:
  database_omunga: 
    image: postgres
    container_name: database_omunga
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=omunga
      - POSTGRES_PASSWORD=pxoW3sFF2t3gArReSs8L
      - POSTGRES_DB=database_omunga
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: omunga_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    command: "yarn dev"
    volumes:
      - .:/usr/app
    network_mode: host
    depends_on:
      - database_omunga


volumes:
  pgdata:
    

