version: '3.7'

services:
  database_omunga: 
    image: postgres
    container_name: database_omunga
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=Docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=omunga
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: omunga_app
    ports:
      - 3000:3000
    restart: always
    command: "yarn dev"
    volumes:
      - .:/usr/app
    network_mode: host
    


volumes:
  pgdata:
    

